### ISSUE TITLE
SHAP Interaction Value Summary Plot

### ISSUE THREAD

**Issue by mao223** [bgreenwell/fastshap#41]
Is there a way to generate the SHAP Interaction Value Summary Plot? For instance:
<img width="1091" alt="Screen Shot 2022-05-27 at 12 43 40 PM" src="https://user-images.githubusercontent.com/26750847/170779603-517f01b1-5fb5-417a-915d-ef64cd71ace5.png">

**Comment by bgreenwell** [comment]
Hi @mao223 the fastshap package does not compute shap interaction values at this time. Not sure if this is a feature that will make it into the package I the future either.
