### ISSUE TITLE
Is it valid to aggregate fastshap values to sets of features?

### ISSUE THREAD

**Issue by py3lee** [bgreenwell/fastshap#43]
Can I check if it is valid to aggregate the fastshap values for related features? 
- For example, 'height' and 'weight' into 'BMI', and 
-  2 related ordinal features into one feature? 

Understand that this is not really an issue but more of a question, but I'm not quite sure where else to post this question as this only pertains to this package. 

Appreciate your help on this! 
Thanks in advance!

**Comment by bgreenwell** [comment]
As long as you set adjust=TRUE then yes, I think it’s perfectly valid to sum the Shapley values across sets of rows or columns. Not sure it makes much sense to aggregate in any other way, such as in your bmi example. In that case, it would be more useful to model the features of interest to explain!

**Comment by py3lee** [comment]
That's great to know, thank you so much!
