### ISSUE TITLE
{lightgbm} v4.0.0 is coming

### ISSUE THREAD

**Issue by jameslamb** [bgreenwell/fastshap#47]
👋 Hello! I'm James, one of the maintainers of LightGBM.

We were excited to see `{fastshap}` add support for LightGBM models. Thanks so much for making it easier for some R users to inspect the characteristics of their data via `{lightgbm}` models!

First, I wanted to let you know that the next release of LightGBM (the entire project, including the R package) will be a major version release with significant breaking changes. See this discussion of v4.0.0: https://github.com/microsoft/LightGBM/issues/5153. We don't have a planned date for that release yet, as we have been struggling from a lack of maintainer attention / activity. But I expect it will be months not weeks from now.

Please open issues at https://github.com/microsoft/LightGBM/issues if there's anything we could do to make `{lightgbm}`  easier to use with  `{fastshap}`.

I'm opening this issue mainly to ask a question. In this period prior to v4.0.0, I'm willing to contribute and maintain the following here:

* patches that make `{fastshap}` compatible with the latest release on CRAN (v3.3.2) and the upcoming release (v4.0.0) so that the next release of `{lightgbm}` isn't disruptive to you
* CI job(s) testing against the latest development version of LightGBM

**Are you open to such contributions?**

Thanks for your time and consideration.

**Comment by bgreenwell** [comment]
Hi @jameslamb, thank you for the heads up regarding changes coming to v4.0 of lightgbm! It looks like @mayer79 already submitted a PR with some fixes. I’m on vacation now but will review next week when I return. 

And yes, very happy to take any contributions to help fastshap continue to support lightgbm!
